### ISSUE TITLE
Question : compression loss ?

### ISSUE THREAD

**Issue by CharlieCheckpt** [malaterre/ets#1]
Hello, 

Thank you for this piece of code, this is very useful for one project I'm working on. 

I am not very familiar with C, and I was wondering: 
Is there any loss due to compression when you save the small patches to disk  (this [line](https://github.com/malaterre/ets/blob/master/dumpets.c#L301))?

**Comment by malaterre** [comment]
@CharlieCheckpt Here is the definition of `fwrite` function:

* https://en.cppreference.com/w/cpp/io/c/fwrite

If any loss is incur by using this function, I guess your best bet is to simply burn your computer...
